### ISSUE TITLE
Too bad its for NTSC Only! 

### ISSUE THREAD

**Issue by 03stevensmi** [jfroco/rpizero_lakka_crt#1]
Why is it every single crt tweak that ever gets released is only for the USA!
Seriously there isn't a single rpi analogue tweak after 2020 that isn't only 420i/240p!

Could you please consider (if not you... Then god hell someone out there)
please support pal (576i/288p) so the majority rest of the world can enjoy this amazing project?

Could I also ask if this will work for the rpi3b too?
Or is it only specifically for the zero.

If you (or someone who knows how and also feels left out by the Americans) could please
Consider support for pal regions... Then consider this the worlds FIRST (and not outdated)
Crt Tweak for the raspberry pi that actually does pal! 
Seriously guys... Look It up! If you can find any thing like this after around 2021
That doesn't just support ntsc... I will literally drink a whole bottle of English mustard! 
There not way in hell anything even semi recent exists!

Cheers man,
I doubt you or anyone will actually give a crap or care...
But I'm still keeping my fingers crossed and wishing for the best!

;)

**Comment by riggles1** [comment]
You are completely mistaken, 50Hz only CRT's are extremely rare. Every EU sold CRT since the early 80s will sync 60Hz, support was standardized alongside Scart RGB, even the smallest lowest end bargain bin no brand 14" TVs had to have that support as it was a EU regulation. 
Only a tiny fraction of rare exceptions exist like ultra portable TV's or things that came from eastern Europe without these regulations. Even in those countries, those are exceptions as the major CRT manufacturers like Philips produced the vast majority of TV's in those territories too, releasing the same stuff there.

RGB uses separate wires for each color instead of encoding them. This isn't NTSC or PAL, this is RGB60 and RGB50 that we're talking about. 

These RGB projects aren't US focused, if anything they're Europe focused because they're RGB, US TV's had composite, s-video and sometimes component instead, they're the ones who need difficult or expensive workarounds for this with RGB mods or transcoders to use this. For European CRT TVs it's just plug and play. The complete opposite of what you're saying.

Unless you have a TV from the 70s, this isn't an issue anyone in Europe encounters. 

Hell, TV's from the 70s are hands on and tend to have a physical vhold potentiometer that you could adjust for 60Hz.
50Hz gaming only existed in the first place for these very few edge cases and people with very old TV's still in their households.
With the Gamecube you even had PAL-region releases that were 60Hz-only like Metroid Prime 2, because they knew that everyone had 60Hz compatible CRT's. (These games had a textbox on the back saying 60Hz only)

50Hz 288p is pointless for a UI to support in 2024. Literally any pickup you can make in Europe will be 60Hz capable, any cheap or free local/FBM etc CRT TV set with a scart input will do it. 
I've picked up and checked CRTs in Sweden for decades, I do CRT maintenance+repairs, 60Hz console mods etc. 60Hz is never an issue with EU TVs unless it's something like a tiny countertop radio-TV with RF only.

The one time I've ever heard of a 50Hz only TV with a Scart port was some weird russian import someone picked up once, the only time in the decades of this hobby that I've seen it.

While I'm at it; the 50Hz on the back label of TVs just mean that they take 50Hz 240V AC, it all gets converted to DC in the TV powersupply, it doesn't mean anything in regards to vertical sync range (refreshrates). (A lot of people don't know this)

50Hz is terrible and the vast vast majority of titles play very poorly at 50Hz, with only a handful of 50Hz optimized games to choose from in comparison to 60.
This project supports those exclusive 50Hz only games thanks to switchres.

We're talking something in the range of 0.1% if that of all CRT TV's existing in Europe that are 50Hz only today.

Kind regards - Riggles CRT Enthusiast - CRT Discord

**Comment by 03stevensmi** [comment]
@riggles1 wow, That... I didn't know. 
Thanks, but i have a few questions
Would that mean that if the interlaced lines are 420i... They will sill display fine on a 576i tv?
Other than bad scaling with the horizontal black lines ofc...

Because its the proper scaling, pal colours and interlacing I'm looking for.
I did not however know that it would show in colour on my TV though.

If the interlaced lines are not supported on a EU TV by this project,
Is there any way to scale them so they look right?
Also most of my crt's i had didn't support rgb. I do have 1 in my room that does I think.
BTW I'm trying to do this for popper amiga display. I've been banging my head against a brink wall
Finding something that just looks right as it would on a real system.

**Comment by riggles1** [comment]
EU sold TV's will do 480i, the linecount is tied to the refresh, the horizontal scan limit of CRT TV's is ~16kHz in the whole world for standard def TV's. That's why 50Hz becomes 576i or 288p, because they need to add more black lines to the signal to pad out and still be 15-16kHz.

So yes, 60Hz content is 480i here in Europe, it can only be a maximum of that and still be standard def.

Colors isn't an issue because this project is for RGB, there is no color encoding like I wrote in the long post above. Color issues are only an issue with composite, RF or s-video, they need to encode color in order to fit the image in a single wire instead of using the separate wires RGB scart uses.

Any CRT TV with scart input will support RGB 480i 60Hz, as well as 576i 50Hz and the various progressive resolutions used by games. 
There is no "proper scaling" there's no scaling at all here, 480i will be 480i, 1:1 perfect output, same with 60Hz 240p or 224p.


As for the Amiga monitor, those technically aren't CRT TV's, they're monitors, so they didn't fall under the EU regulations for RGB Scart and 60Hz, those regulations just applied to CRT TV's. They can one of the very edge case exceptions. 

With the Amiga 1080 monitor however has an adjustable pot inside (vhold) to make it sync to 60Hz, but I get that this is annoying considering the Amiga a platform with a lot of 50Hz only games.

I would close this issue and open a new issue/feature request to specifically mention that you wish there was an Amiga monitor focused project with a 50Hz UI. Since the rest of what you said is incorrect in regards to CRT's in Europe not supporting 60Hz and the project being US focused, when in reality it's easier for Europeans because it's RGB60.

If you use a CRT TV instead of an Amiga monitor you can play any Amiga+CD32 game properly at proper 50Hz (and the Amiga games like Fury of Furries that did 60Hz too) and any other NTSC-U/J console game at 60Hz no problem, all with a 60Hz UI.
The CRT Switchres feature of this project (modeline switching) will automatically set 50Hz when needed.

**Comment by 03stevensmi** [comment]
@riggles1 The crt I have is a Phillips 14PV200/07.
It has scart as input.
Just trying it now with my Bush crt and your right, it does display...
However I just hooked it up with the Philips and nothing! Just a black screen. There's no rgb channel or anything.
So I don't think that's 100% true that all crt with scart does rgb.
Maybe if I was to mess about in the service menu... But I'd rather die from food poisoning that burn to death in a fire. 

I did find this 7 year old crt HDMI timing setting for uae4arm:
1920 282 49.920410 6 4 11 48 192 240 5 15650
https://github.com/Sir-Ironic/RPi-Hdmi_Timings
Would that be any good, BTW I'm making a new topic for this... Will post a link here in a bit 
and close this topic, thanks

**Comment by riggles1** [comment]
The issue with the philips isn't due to not syncing 60Hz, it had to be able to, and it's a major manufacturer even and not some weird russian import TV. It will be true with that set. They even advertise NTSC (60Hz composite VHS playback) on the manual cover https://www.manualslib.com/manual/123621/Philips-14pv200.html

Connect a 60Hz capable console (modded, or use something like a Wii) with a properly wired Scart cable and that Philips work with 60Hz. 

What I'm suspecting is that you aren't feeding that CRT 12V on the blanking line of the scart port (pin8), necessary for a lot of TV's in order to switch to RGB mode. On other CRT TV's you have an RGB channel or a remote button for it, but some need this 12V to display RGB. It's the standard for Scart, manufacturers had to do it because of strict EU regulations.

The other issue could be a damaged Scart port or some other component in the TV being bad preventing the RGB switch, CRT's are old and often need maintenance, soldering cold joints, replacing capacitors.

What also (less likely) could be wrong or more off-spec are the range timings generated through this project that you're feeding it (monitor range settings, timings, modelines, not sure how they handle it for this project) where sync, porch front+back signals are adjusted through those timing values.

**Comment by 03stevensmi** [comment]
@riggles1 I'm betting on the 12v thing. As it works fine on the Bush TV with rgb channel, but the Phillips doesn't want to display any rgb signal. I doubt its the timings because it looks fine on my Bush (apart from the Black bars at the top & bottom of the screen).

How do I do 12v from my rpi hdmi>vga to scart... to my phillips? I'm only asking because I've never heard this being a thing though. I did try another scart cable, but I got the same issue. I do have 1 single ntsc vhs tape (no idea how the hell I ended up having it) and your right, it plays fine. Just not rgb.

BTW, the topic for the 50Hz games request is here: https://github.com/jfroco/rpizero_lakka_crt/issues/2

**Comment by riggles1** [comment]
The VGA Scart adapter or whatever you're using isn't doing 12V on pin8 probably, you can measure it with a multimeter. Properly wired RGB scart cables for game consoles will do this. If there is no 12V from this pin, then you could get a scart switch (https://m.media-amazon.com/images/I/61kCz2dJ8HL.jpg this exact PCB layout, different shells), these are purely mechanical switches that don't introduce issues or noise. You can cut the pin8 trace for the output Scart port, and inject your own 12V there (power supply).

Done that scart switch mod before for TV's that can't be switched to RGB through the remote, or sense RGB another way.

Some TV's don't need this 12V blanking to auto switch to RGB.

**Comment by 03stevensmi** [comment]
@riggles1 Ahh so thats what that plugs for. I always wondered why that was included with a 12v adapter. That must be the issue. One of my HDMI to vga had 12v with a cable, but the one I'm using now doesn't. Its worth mentioning that the vga to scart also has 12v. I may have to buy another HDMI to vga from ebay, but yes that must be the problem. Come to think of it, I don't think I actually tested it with that 12V vga adapter. Unfortunately that adapter broke. So ill have to get another one with 12v. As for my issue, its still unsolved but has nothing to do with what I thought was the problem. So I've moved this issue to here: https://github.com/jfroco/rpizero_lakka_crt/issues/2 and gonna close this one as its unrelated. Thanks man. I appreciate your help. Seriously its been hell trying to Google this problem for a solution. Lets just hope that someday i get it working.
